#!/usr/bin/env bash

BUILD="x86"
BUILD_TYPE="release"
BUILD_WINDOWS="no"
OPENGL_DEFINE=""
OPENGL_LIBS="-lGL"
ANDROID_INSTALL="no"
CPP_LTO="-flto"

OS=$(uname)

function compile_x86
{
	CPU_FLAGS='-mno-sse2 -mno-sse -mno-mmx'
	COMMON_FLAGS='-Wall -m32 -std=gnu89'

	echo -n "Building"
	if [[ $BUILD_TYPE == "debug" ]]; then
		echo -n " debug"
		WIN_SUBSYSTEM='console'
		DEBUG_ASM='-g dwarf2'
		C_FLAGS="$COMMON_FLAGS -g $CPU_FLAGS"
	else
		echo -n " release"
		WIN_SUBSYSTEM='windows'
		C_FLAGS="$COMMON_FLAGS -O2 $CPU_FLAGS"
		STRIP='-s'
	fi

	rm -f *.o

	echo -n " for"
	if [[ $BUILD_WINDOWS == "yes" ]]; then
		echo -n " Windows... "
		i686-w64-mingw32-windres Windows/nfs2se.rc icon.o &&
		i686-w64-mingw32-gcc $C_FLAGS $OPENGL_DEFINE -c *.c &&
		yasm -f win32 Asm/NFS2SE.asm -o NFS2SE.Win32.o $DEBUG_ASM --prefix=_ &&
		i686-w64-mingw32-ld --enable-stdcall-fixup -o "../Need For Speed II SE/nfs2se.exe" *.o --stack=0x7D00,0x7D00 --heap=0x2000,0x1000 -lws2_32 -lwinmm -lmingwex -lmsvcrt -lkernel32 -lopengl32 -lSDL2 -subsystem=$WIN_SUBSYSTEM $STRIP -e _start &&
		rm -f *.o &&
		echo "OK!"
	else
		if [ $OS == "Darwin" ]; then
			echo -n " macOS... "
			clang $C_FLAGS $OPENGL_DEFINE -DSTACK_REALIGN -DSWAP_WINDOW_AND_GL_THREAD -c *.c -mmacosx-version-min=10.6 &&
			yasm -f macho Asm/NFS2SE.asm -o NFS2SE.OSX.o --prefix=_ -DSWAP_WINDOW_AND_GL_THREAD &&
			ld -o "../Need For Speed II SE/nfs2se" *.o -lc -lSDL2 -framework OpenGL -macosx_version_min 10.6 -e _start &&
			rm -f *.o &&
			echo "OK!"
		else
			if [ -z $CC ]; then
				CC=gcc
			fi
			echo -n " $OS ($CC)... "
			yasm -f elf32 Asm/NFS2SE.asm -o NFS2SE.Elf32.o $DEBUG_ASM &&
			$CC -no-pie -nostartfiles $C_FLAGS -DSTACK_REALIGN $OPENGL_DEFINE -o "../Need For Speed II SE/nfs2se" NFS2SE.Elf32.o *.c -lSDL2 $OPENGL_LIBS $STRIP -Wl,-rpath=\$ORIGIN -Wl,-estart &&
			rm -f NFS2SE.Elf32.o &&
			echo "OK!"
		fi
	fi
}

function compile_cpp
{
	if [ $(uname -m) == "x86_64" ]; then
		CPU_FLAGS="-m32"
	fi

	if [[ $BUILD_TYPE == "debug" ]]; then
		FLAGS="-O0 -g"
		CPP_LTO=""
		echo "Debug"
	else
		FLAGS="-O3 -DNDEBUG"
		echo "Release"
	fi

	echo -n "Compiling C++ code... "
	clang -c -std=c++14 $CPU_FLAGS $CPP_LTO $FLAGS -Wno-c++11-narrowing -Wextra Cpp/NFS2SE.cpp -fno-rtti -fno-exceptions || exit
	echo "OK!"

	echo -n "Compiling C code... "
	clang -c -std=gnu89 -Wno-incompatible-function-pointer-types -Wno-int-conversion -Wall $CPU_FLAGS $FLAGS $OPENGL_DEFINE -DNFS_CPP *.c || exit
	echo "OK!"

	echo -n "Linking... "
	clang -fuse-ld=lld -o "../Need For Speed II SE/nfs2se" $CPU_FLAGS $CPP_LTO *.o -lSDL2 $OPENGL_LIBS -lm || exit
	echo "OK!"

	if [[ $BUILD_TYPE != "debug" ]]; then
		echo -n "Stripping... "
		strip "../Need For Speed II SE/nfs2se" || exit
		echo "OK!"
	fi

	rm -f *.o
}

function compile_wasm
{
	if ! command -v emcc >/dev/null 2>&1 || ! command -v em++ >/dev/null 2>&1; then
		echo "Emscripten is not available. Activate emsdk before building." >&2
		exit 1
	fi

	if [[ $BUILD == "web" ]]; then
		WASM_BUILD_DIR="${WASM_BUILD_DIR:-../build/web-public/game}"
		WASM_OBJ_DIR="${WASM_OBJ_DIR:-../build/web-obj}"
		WASM_OUTPUT="$WASM_BUILD_DIR/nfs2se.js"
		WASM_SHELL_FLAGS=()
		WASM_GAME_FLAGS=(
			--embed-file "../Need For Speed II SE/install.win@/NFSIISE/install.win"
			--embed-file "../Need For Speed II SE/text.eng@/NFSIISE/text.eng"
			--embed-file "../Need For Speed II SE/text.fre@/NFSIISE/text.fre"
			--embed-file "../Need For Speed II SE/text.ger@/NFSIISE/text.ger"
			--embed-file "../Need For Speed II SE/text.ita@/NFSIISE/text.ita"
			--embed-file "../Need For Speed II SE/text.spa@/NFSIISE/text.spa"
			--embed-file "../Need For Speed II SE/text.swe@/NFSIISE/text.swe"
			--embed-file "../Need For Speed II SE/nfs2se.conf.template@/NFSIISE/nfs2se.conf.template"
		)
	else
		WASM_BUILD_DIR="${WASM_BUILD_DIR:-../build/wasm}"
		WASM_OBJ_DIR="${WASM_OBJ_DIR:-$WASM_BUILD_DIR/obj}"
		WASM_OUTPUT="$WASM_BUILD_DIR/nfs2se.html"
		WASM_SHELL_FLAGS=(--shell-file Wasm/shell.html)
		WASM_GAME_FLAGS=(--preload-file "../Need For Speed II SE@/NFSIISE")
	fi
	mkdir -p "$WASM_OBJ_DIR" || exit
	rm -f "$WASM_OBJ_DIR"/*.o
	rm -f "$WASM_BUILD_DIR/nfs2se.data" "$WASM_BUILD_DIR/nfs2se.html" \
		"$WASM_BUILD_DIR/nfs2se.js" "$WASM_BUILD_DIR/nfs2se.wasm" \
		"$WASM_BUILD_DIR/nfs2se.wasm.map"

	WASM_DEFINES="-DNFS_CPP -DGLES2 -DNFS_NO_NETWORK"
	WASM_COMMON_FLAGS="-pthread $WASM_DEFINES -fno-strict-aliasing"
	WASM_SDL_FLAGS="--use-port=sdl2"
	if [[ $BUILD_TYPE == "debug" ]]; then
		WASM_OPT_FLAGS="-O0 -gsource-map"
		WASM_LINK_DEBUG_FLAGS="--profiling-funcs"
		WASM_ASSERTIONS=2
	else
		if [[ $BUILD == "web" ]]; then
			WASM_OPT_FLAGS="-O2 -DNDEBUG"
		else
			WASM_OPT_FLAGS="-O3 -DNDEBUG -flto"
		fi
		WASM_LINK_DEBUG_FLAGS=""
		WASM_ASSERTIONS=0
	fi

	echo -n "Compiling C++ code for wasm32... "
	WASM_CPP_SOURCE="$WASM_OBJ_DIR/NFS2SE.cpp"
	cp Cpp/NFS2SE.cpp "$WASM_CPP_SOURCE" || exit
	patch -s "$WASM_CPP_SOURCE" Wasm/NFS2SE.patch || exit
	python3 Wasm/fix_translated_abi.py "$WASM_CPP_SOURCE" || exit
	em++ -c -std=c++14 $WASM_COMMON_FLAGS $WASM_OPT_FLAGS \
		-Wno-c++11-narrowing -fno-rtti -fno-exceptions \
		"$WASM_CPP_SOURCE" -o "$WASM_OBJ_DIR/NFS2SE.o" || exit
	echo "OK!"

	WASM_C_SOURCES=(
		DInput.c
		EAcsnd.c
		FetchTrackRecords.c
		Glide2x.c
		Kernel32.c
		Timer.c
		User32.c
		WinMM.c
		Wrapper.c
		Wasm/Wsock32.c
	)

	echo -n "Compiling C wrapper code for wasm32... "
	for source in "${WASM_C_SOURCES[@]}"; do
		object_name=${source//\//_}
		emcc -c -std=gnu89 $WASM_COMMON_FLAGS $WASM_OPT_FLAGS $WASM_SDL_FLAGS \
			-Wall -Wno-incompatible-function-pointer-types -Wno-int-conversion \
			"$source" -o "$WASM_OBJ_DIR/${object_name%.c}.o" || exit
	done
	echo "OK!"

	echo -n "Linking WebAssembly app... "
	em++ "$WASM_OBJ_DIR"/*.o $WASM_OPT_FLAGS $WASM_LINK_DEBUG_FLAGS -pthread \
		$WASM_SDL_FLAGS \
		"${WASM_SHELL_FLAGS[@]}" \
		"${WASM_GAME_FLAGS[@]}" \
		-lidbfs.js \
		-sALLOW_MEMORY_GROWTH=1 \
		-sINITIAL_MEMORY=134217728 \
		-sMAXIMUM_MEMORY=1073741824 \
		-sSTACK_SIZE=1048576 \
		-sPTHREAD_POOL_SIZE=8 \
		-sPROXY_TO_PTHREAD=1 \
		-sOFFSCREENCANVAS_SUPPORT=1 \
		-sEMULATE_FUNCTION_POINTER_CASTS=1 \
		-sFULL_ES2=1 \
		-sFORCE_FILESYSTEM=1 \
		-sEXPORTED_RUNTIME_METHODS="['FS','IDBFS','addRunDependency','removeRunDependency','HEAPU8']" \
		-sEXIT_RUNTIME=0 \
		-sASSERTIONS=$WASM_ASSERTIONS \
		-sMIN_WEBGL_VERSION=1 \
		-sMAX_WEBGL_VERSION=2 \
		-o "$WASM_OUTPUT" || exit
	echo "OK!"
	if [[ $BUILD == "web" ]]; then
		echo "Run: cd src/Web && npm install && npm run build"
	else
		echo "Run: python3 src/Wasm/serve.py build/wasm"
	fi
}

while (( $# > 0 ))
do
	key=$1
	case $key in
		cpp|android|wasm|web)
			BUILD=$key
		;;
		debug)
			BUILD_TYPE="debug"
		;;
		win32)
			BUILD_WINDOWS="yes"
		;;
		gl1)
			OPENGL_DEFINE="-DOPENGL1X"
		;;
		gles2)
			OPENGL_DEFINE="-DGLES2"
			OPENGL_LIBS="-lGLESv2"
		;;
		install)
			ANDROID_INSTALL="yes"
		;;
	esac
	shift
done

cd src || exit

if [[ $BUILD != "android" && $BUILD != "wasm" && $BUILD != "web" ]]; then
	if [[ $OPENGL_DEFINE == "-DOPENGL1X" ]]; then
		echo "Building OpenGL 1"
	elif [[ $OPENGL_DEFINE == "-DGLES2" ]]; then
		if [[ $OS == "Darwin" ]]; then
			echo "OpenGL|ES 2 is not supported on macOS"
			exit 1
		fi
		if [[ $BUILD_WINDOWS == "yes" ]]; then
			echo "OpenGL|ES 2 is not supported on Windows"
			exit 1
		fi
		echo "Building OpenGL|ES 2"
	else
		echo "Building OpenGL 2"
	fi
fi

if [[ $BUILD == "cpp" ]]; then
	if [[ $OS == "Darwin" ]]; then
		echo "C++ translation is not supported on macOS"
		exit 1
	fi
	if [[ $BUILD_WINDOWS == "yes" ]]; then
		echo "C++ translation is not supported on Windows"
		exit 1
	fi
	compile_cpp $@
elif [[ $BUILD == "wasm" || $BUILD == "web" ]]; then
	compile_wasm
elif [[ $BUILD == "android" ]]; then
	VERSION=$(grep WRAPPER_VERSION "Version" | cut -c26-30 | grep "\.") || exit
	cd Android || exit
	echo "Building OpenGL|ES 2 for Android, wrapper version: $VERSION"
	sed "s/@VERSION@/$VERSION/" app/src/main/AndroidManifest.xml.in > app/src/main/AndroidManifest.xml || exit
	rm -f app/build/outputs/apk/debug/app-debug.apk || exit
	./gradlew packageDebug || exit # packageRelease if you want to sign it
	if [[ $ANDROID_INSTALL == "yes" ]]; then
		adb install -r app/build/outputs/apk/debug/app-debug.apk || exit
		sleep 0.25
		adb shell am start -n org.zaps166.NFSIISE/org.zaps166.NFSIISE.NFSIISE
	fi
else
	compile_x86 $@
fi
